version: '1'
services:
  # MongoDB container
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./components/db:/data/db  # Persist MongoDB data
    networks:
      - backend-network  

  # Spring Boot application
  buiness-app:
    image: restaurant-backend:latest
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - backend-network  # Create a custom network for backend communicationb

networks:
  backend-network:
   driver: bridge
