version: '1'
services:
  # MongoDB container
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./components/db:/data/db  # Persist MongoDB data
    networks:
      - backend-network  

  # Spring Boot application
  spring-backend:
    image: restaurant-backend:latest
    container_name: spring-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - backend-network 
  angular-frontend:
    image: restaurant-frontend:latest
    container_name: spring-frontend
    ports:
      - "4200:4200"
    depends_on:
      - spring-backend
    networks:
      - backend-network 
networks:
  backend-network:
   driver: bridge
