/**
 * Swagger Restaurant
 * This is a sample Restaruant
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';


export interface CustomerDetails { 
    userId?: string;
    name: string;
    email?: string;
    mobil?: string;
    address?: string;
    company?: string;
    tax?: string;
    points?: number;
    orders?: Array<Order>;
}

