/**
 * Swagger Restaurant
 * This is a sample Restaruant
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FoodRecipeInner } from './foodRecipeInner';


export interface Food { 
    id: string;
    name: string;
    type: Food.TypeEnum;
    price: number;
    recipe?: Array<FoodRecipeInner>;
}
export namespace Food {
    export type TypeEnum = 'main course' | 'dessert' | 'side dish' | 'soup';
    export const TypeEnum = {
        MainCourse: 'main course' as TypeEnum,
        Dessert: 'dessert' as TypeEnum,
        SideDish: 'side dish' as TypeEnum,
        Soup: 'soup' as TypeEnum
    };
}


