/**
 * Swagger Restaurant
 * This is a sample Restaruant
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    name: string;
    role?: User.RoleEnum;
}
export namespace User {
    export type RoleEnum = 'waiter' | 'manager' | 'customer';
    export const RoleEnum = {
        Waiter: 'waiter' as RoleEnum,
        Manager: 'manager' as RoleEnum,
        Customer: 'customer' as RoleEnum
    };
}


