/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.0.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package bme.restaurant.api;

import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-11-23T22:27:38.107543100+01:00[Europe/Budapest]")
@Validated
@Tag(name = "user", description = "the user API")
public interface PasswordResetApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * PATCH /password-reset : Password reset
     *
     * @param userId The ID of the user (required)
     * @param oldPassword  (required)
     * @param newPassword  (required)
     * @return successfully updated (status code 200)
     *         or Unauthorized (status code 401)
     *         or Invalid request (status code 400)
     */
    @Operation(
        operationId = "passwordReset",
        summary = "Password reset",
        tags = { "user" },
        responses = {
            @ApiResponse(responseCode = "200", description = "successfully updated"),
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
            @ApiResponse(responseCode = "400", description = "Invalid request")
        },
        security = {
            @SecurityRequirement(name = "sessionId")
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/password-reset"
    )
    default ResponseEntity<Void> passwordReset(
        @NotNull @Parameter(name = "userId", description = "The ID of the user", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "userId", required = true) String userId,
        @NotNull @Parameter(name = "oldPassword", description = "", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "oldPassword", required = true) String oldPassword,
        @NotNull @Parameter(name = "newPassword", description = "", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "newPassword", required = true) String newPassword
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
