export * from './auth.service';
import { AuthService } from './auth.service';
export * from './booking.service';
import { BookingService } from './booking.service';
export * from './customer.service';
import { CustomerService } from './customer.service';
export * from './default.service';
import { DefaultService } from './default.service';
export * from './employee.service';
import { EmployeeService } from './employee.service';
export * from './menu.service';
import { MenuService } from './menu.service';
export * from './table.service';
import { TableService } from './table.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AuthService, BookingService, CustomerService, DefaultService, EmployeeService, MenuService, TableService, UserService];
